spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/testdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop
